/**
 * Extracts only the Streamline Freehand icons we actually use into a generated
 * TS module, so the app ships ~10KB of SVG instead of the 2.6MB icon set and
 * never fetches icon data at runtime.
 *
 * Icons: Streamline Freehand, CC BY 4.0 — https://streamlinehq.com
 * Attribution is required and lives in the site footer and README.
 *
 * Run:  npm run icons
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(here, '../node_modules/@iconify-json/streamline-freehand/icons.json')
const OUT = resolve(here, '../src/components/icons/freehand.gen.ts')

/** Every Freehand icon the app uses. Keep alphabetical. */
const WANTED = [
  'alerts-stop-sign',
  'business-deal-handshake',
  'lock-key-1',
  'money-wallet',
  'receipt',
  'search-magnifier',
  'security-shield-wall',
  'share-radar',
  'tag-sale-price',
  'upload-brackets',
  'video-game-controller',
]

const set = JSON.parse(readFileSync(SRC, 'utf8'))
const w = set.width ?? 24
const h = set.height ?? 24

const missing = WANTED.filter((n) => !set.icons[n])
if (missing.length) {
  console.error(`✕ not in the free Freehand set: ${missing.join(', ')}`)
  process.exit(1)
}

const entries = WANTED.map((name) => {
  const icon = set.icons[name]
  const box = `0 0 ${icon.width ?? w} ${icon.height ?? h}`
  // JSON.stringify handles the quoting/escaping of the raw SVG body.
  return `  '${name}': { box: '${box}', body: ${JSON.stringify(icon.body)} },`
}).join('\n')

const out = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: @iconify-json/streamline-freehand (Streamline Freehand, CC BY 4.0)
// Regenerate with: npm run icons

export type FreehandName =
${WANTED.map((n) => `  | '${n}'`).join('\n')}

export const freehandIcons: Record<FreehandName, { box: string; body: string }> = {
${entries}
}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, out, 'utf8')
console.log(`✓ ${WANTED.length} icons → src/components/icons/freehand.gen.ts`)
